name: Build, Test and Publish for Lab 5

on:
  push:
    branches: [lab5] # Убедитесь, что ваша ветка называется lab5, или main

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE_PATH: . # Путь к файлу .sln. Если он в корне, то оставляем '.', иначе указываем папку

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE_PATH }} --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{ env.SOLUTION_FILE_PATH }} --verbosity normal

    - name: Publish application
      run: dotnet publish ./OnlineCoursesMVC/OnlineCoursesMVC.csproj --configuration Release --output ./publish --no-build
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.os }}
        path: ./publish 
        retention-days: 30